DROP TABLE IF EXISTS WithEx CASCADE;
DROP TABLE IF EXISTS WithEq CASCADE;
DROP TABLE IF EXISTS WithGr CASCADE;
DROP TABLE IF EXISTS Exercise CASCADE;
DROP TABLE IF EXISTS Workout CASCADE;
DROP TABLE IF EXISTS Equipment CASCADE;
DROP TABLE IF EXISTS ExerciseGroup CASCADE;
